name: tuesdae_rush
description: "Tuesdae Rush - Traffic Control Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  firebase_core: ^3.14.0
  firebase_analytics: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true
  assets:
      - assets/images/grass_texture.jpg
      - assets/images/tuesdae_rush_cover.jpg
      - assets/audio/

flutter_launcher_icons:
  windows:
    generate: true
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

