// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Hardcoded Firebase configuration values
  static const String _webApiKey = 'AIzaSyARJjeYc4M0lIRbYVwFNBzhp6DoBl7yPIk';
  static const String _webAppId = '1:300081682240:web:ffe6ee1008e8ce7fe18ca5';
  static const String _messagingSenderId = '300081682240';
  static const String _projectId = 'tuesdaerush';
  static const String _storageBucket = 'tuesdaerush.firebasestorage.app';
  static const String _authDomain = 'tuesdaerush.firebaseapp.com';
  static const String _measurementId = 'G-QDWQG17Z79';

  static const String _androidApiKey =
      'AIzaSyBNgz5KrpuxrVxOJk02FSeRvWQDzdFdnPc';
  static const String _androidAppId =
      '1:300081682240:android:a916c2a2370e5fa8e18ca5';

  static const String _iosApiKey = '1:300081682240:ios:53dc1cec4c27c017e18ca5';
  static const String _iosAppId = '1:300081682240:ios:53dc1cec4c27c017e18ca5';

  static const String _macosApiKey =
      '1:300081682240:ios:53dc1cec4c27c017e18ca5';
  static const String _macosAppId = '1:300081682240:ios:53dc1cec4c27c017e18ca5';

  static const String _windowsApiKey =
      'AIzaSyARJjeYc4M0lIRbYVwFNBzhp6DoBl7yPIk';
  static const String _windowsAppId =
      '1:300081682240:web:3252e3ab8e08ae76e18ca5';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: _webAppId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    authDomain: _authDomain,
    storageBucket: _storageBucket,
    measurementId: _measurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: _androidAppId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: _iosAppId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
    iosBundleId: 'games.tuesdae.tuesdae-rush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _macosApiKey,
    appId: _macosAppId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
    iosBundleId: 'games.tuesdae.tuesdae-rush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _windowsApiKey,
    appId: _windowsAppId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    authDomain: _authDomain,
    storageBucket: _storageBucket,
  );
}
